### PR TITLE
replaced html reserved characters

### PR DESCRIPTION
**Pull request by samarth8765**
Signed-off-by: Samarth <samdhawan8765@gmail.com>

hey I have replaced HTML reserved characters

### CODE REVIEW

**Comment by guimspace** [comment]
Thanks! I'm ready to merge, but the DCO requires your full name in the signed-off part. Can you amend your commit please?

**Comment by samarth8765** [comment]
I have signed-off my name.Initially when I made my first PR it was showing "All checks are not passed" then I deleted that and created this new one with signed off..

**Comment by guimspace** [comment]
The signed-off has your first name, but your last name is missing. You can fix that with a `git --amend`, and then force-push again.

**Comment by samarth8765** [comment]
Now please check I have amend my last name

**Comment by guimspace** [comment]
Thanks, I added your patch to my git tree. It will show up in the next release of the add-on.

**Comment by samarth8765** [comment]
Thanks, Btw I'm new to open source community.Can you please tell me some more repos where I can contribute as a beginner.

**Comment by guimspace** [comment]
@samarth8765 This is my main repository, feel free to analyze it and propose any changes. Regarding other projects, maybe [The Odin Project](https://github.com/TheOdinProject) might interest you - check their website to learn what it is about. A Linux kernel patch might interest you as well ([video](https://www.youtube.com/watch?v=LLBrBBImJt4)).

**Pull request closed without merging**
